### ISSUE TITLE
The GPS status is always -1.

### ISSUE THREAD

**Issue by qazmichaelgw** [KumarRobotics/ublox#10]
When I use Ublox EVK_M8L by this driver.
I check the navstatus:

```
iTOW: 282172800
gpsFix: 0
flags: 76
fixStat: 0
flags2: 0
ttff: 0
msss: 1270359
```

The gpsFix is always 0. Which means that there is no fix. But the EVK_M8L model supports 3d dead reckoning. Is there any way to fix this problem?

**Comment by vmlane** [comment]
this value was hardcoded in for that commit, it's been fixed in the last commit.

**Comment by PratNag** [comment]
Hello @qazmichaelgw Can you share any info about how you configured to use M8L?
