### ISSUE TITLE
rtcm_msgs Dependency erros

### ISSUE THREAD

**Issue by RoboEvangelist** [KumarRobotics/ublox#138]
Folks,

I can't compile cause I can't find rtcm_msgs. @versatran01 and markovigor might know about this?

Thanks

**Comment by Timple** [comment]
At the end of today, you should be able to do `apt install ros-noetic-rtcm-msgs` [source](https://discourse.ros.org/t/preparing-for-noetic-sync-2021-08-13/21806).

For shorter-term solution you can install from source: https://github.com/tilk/rtcm_msgs

**Comment by Timple** [comment]
Alright, that took a little while longer, but you can `apt install ros-noetic-rtcm-msgs` now.

**Comment by RoboEvangelist** [comment]
Groovy! Thanks!
