### ISSUE TITLE
Getting an issue with navSOL.h not existing

### ISSUE THREAD

**Issue by eselkin** [KumarRobotics/ublox#14]
When building this as a module, I'm getting no such file errors. Is this header file no longer contained in ROS or this project? I see it here http://docs.ros.org/fuerte/api/ublox_msgs/html/NavSOL_8h_source.html in Fuerte, but nowhere else.

**Comment by kartikmohta** [comment]
The header is generated from the msg file here: https://github.com/KumarRobotics/ublox/blob/master/ublox_msgs/msg/NavSOL.msg. Is the `ublox_msgs` package not compiled?

**Comment by eselkin** [comment]
It wasn't getting compiled. Thanks, we traced the problem.
