### ISSUE TITLE
Galactic optional parameter error.

### ISSUE THREAD

**Issue by spikyknox** [KumarRobotics/ublox#145]
In the galactic-devel branch, if I don't set some optional parameter the node crash with : 

```
[ublox_gps_node-1] terminate called after throwing an instance of 'rclcpp::ParameterTypeException'
[ublox_gps_node-1]   what():  expected [integer_array] got [not set]
```
I think the bug have been introduced with the addition of the static type during, the get_parameter needs a default param.
  
```
  this->declare_parameter<std::vector<int64_t>>("rtcm.ids");
  this->declare_parameter<std::vector<int64_t>>("rtcm.rates");
```

**Comment by clalancette** [comment]
@spikyknox I don't have my ublox hardware handy, but can you give #146 a try?  I believe it will solve the issue.

**Comment by spikyknox** [comment]
I give it a try and it indeed solve the problem Thanks @clalancette !

**Comment by clalancette** [comment]
Great, thanks for testing.

**Comment by spikyknox** [comment]
I don't know if it's related but parameter <<nmea.version>> is missing.
