### ISSUE TITLE
Ntrip client to recieve correction data

### ISSUE THREAD

**Issue by felrock** [KumarRobotics/ublox#150]
Ḯm using a zed-f9p and i would like to receive correction data from an ntrip caster, so i need a ntrip client and then apply the received correction. I found this related [pr](https://github.com/KumarRobotics/ublox/pull/136), but it seems to send rtcm and not receive it. Is there another repo that could aid here?

**Comment by stan-guer** [comment]
I used this and it works:
https://github.com/ros-agriculture/ntrip_ros

**Comment by fcladera** [comment]
After #136, we have successfully tested this feature using [https://github.com/LORD-MicroStrain/ntrip_client](https://github.com/LORD-MicroStrain/ntrip_client). Here is an example launch that is compatible with this package:

```
roslaunch ntrip_client ntrip_client.launch host:=your_host  mountpoint:=your_mountpoint username:=your_username password:=your_password rtcm_message_package:=rtcm_msgs
```

**Comment by TobiMiller** [comment]
@fcladera but how to set the config in ublox package? 

https://github.com/KumarRobotics/ublox/blob/master/ublox_gps/src/node.cpp#L1255

The code starts an subscription but param is called "publish" ?! it is misleading. can yo provide me the right instructions for the config.yaml and on which topic i have to publish the rtcm messages? Thank you

**Comment by fcladera** [comment]
Yes, that's correct. The NTRIP client publishes to `/rtcm`.

**Comment by euge2838** [comment]
@Squizzy911 did you solve this issue? I have the same one.

**Comment by pieterblok** [comment]
> After #136, we have successfully tested this feature using https://github.com/LORD-MicroStrain/ntrip_client. Here is an example launch that is compatible with this package:
> 
> ```
> roslaunch ntrip_client ntrip_client.launch host:=your_host  mountpoint:=your_mountpoint username:=your_username password:=your_password rtcm_message_package:=rtcm_msgs
> ```

@fcladera thanks for the update! 

I'm currently using the NTRIP client of RTKLIB (https://github.com/rtklibexplorer/RTKLIB.git), but I want to switch to the NTRIP client of LORD-MicroStrain in ROS2. Doesn't this LORD-MicroStrain option need the output specification (-out)? And how can I properly convert this RTKLIB code to the LORD-MicroStrain one?

```terminal
./str2str -in ntrip://guest:guest@160.16.134.72:80/CQ-UBLOX -out serial://ttyACM0:230400
```

This is the format: ntrip://[username]:[password]@[host]:[port]/[mountpoint]

Maybe I missed it, but there's no clear example on the LORD-MicroStrain git. Thank you!
