### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by GaneshGovind1** [KumarRobotics/ublox#166]
roslaunch ublox/ublox_gps/launch/ublox_device.launch 
... logging to /home/ganesh/.ros/log/918ef9e2-f2f9-11ec-a98e-0de060e6af99/roslaunch-GG-23403.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Resource not found: The following package was not found in <arg name="param_file_dir" doc="directory to look for $(arg param_file_name).yaml" default="$(find ublox_gps)/config"/>: ublox_gps
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/home/ganesh/catkin_ws_kumar_ublox_ros/src
ROS path [2]=/home/ganesh/catkin_ws/src
ROS path [3]=/opt/ros/noetic/share
The traceback for the exception was written to the log file

**Comment by fcladera** [comment]
Did you source your env after installing the package? This seems to be an issue with your env, and not a particular issue of the package.
