### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by willcbaker** [KumarRobotics/ublox#168]
Hello, the code in this repository is listed as BSD License in the package's files, however no LICENSE file is supplied. Would you be able to add a license file to complete this package as open source w/ BSD?

Perhaps https://opensource.org/licenses/BSD-3-Clause ?

**Comment by versatran01** [comment]
I created #174 , will be merged if there's no objection.

**Comment by fcladera** [comment]
Fixed by #175
