### ISSUE TITLE
ublox pps without fix 

### ISSUE THREAD

**Issue by ManChrys** [KumarRobotics/ublox#184]
Hello guys,

i have a ublox 8 and i would like to know how can i achieve pps without gnss fix. I would like to keep pps after losing fix. I would like to keep printing UTC time so i achieve ublox and lidar integration(ROS) so i have the right timestamps.

How could be the right config file for this job ?

Thanks in advance.

**EDIT**

I tried to enable UBX-CFG-TP5 through u-center in windows but nothing happens. ([https://content.u-blox.com/sites/default/files/products/documents/u-blox8-M8_ReceiverDescrProtSpec_UBX-13003221.pdf](url)) (header:19.5 Configuring time pulse with UBX-CFG-TP5, page 74)

**EDIT2**

If i poll TP5 i have this only for 1 epoch after that no more TP5 messages. Also TP5 looks like it has lack of data. Is any other package must so TP5 works ?

![1](https://user-images.githubusercontent.com/67521662/189543405-550167b3-8646-4a7d-9dbd-bae5ccfec271.png)

**Comment by fcladera** [comment]
What are your configurations? Are you able to generate the expected behavior of the PPS pin without using this repo?
