### ISSUE TITLE
Catkin Dependency

### ISSUE THREAD

**Issue by JosephSpires** [KumarRobotics/ublox#189]
Hi,

I am trying to build this on ROS2 humble on Ubuntu 22.04, but 

"rosdep install -i --from-path src --rosdistro humble -y" 

returns:

ublox_msgs: Cannot locate rosdep definition for [message_runtime]
ublox_msg_filters: Cannot locate rosdep definition for [catkin]
ublox_gps: Cannot locate rosdep definition for [tf]
ublox_serialization: Cannot locate rosdep definition for [roscpp_serialization]
ublox: Cannot locate rosdep definition for [catkin]

I tried to install catkin and have been met with:

The following packages have unmet dependencies:
 python-catkin-pkg-modules : Conflicts: catkin but 0.7.8-1 is to be installed
 python-catkin-pkg : Conflicts: catkin but 0.7.8-1 is to be installed

...I've tried a few things but no joy.

Any idea what I'm doing wrong?

Cheers
Joe

**Comment by ralwing** [comment]
I've the same error, 
seems like it's fixed only in `galactic-devel` branch. However on galactic version different error appears:

**Comment by JosephSpires** [comment]
> I've the same error, seems like it's fixed in `galactic-devel` and `ros2` branches.

Yeah I have got it to build in the past with git clone -b ros2 ...



> Hey !
> 
> I am getting the following error

I am also getting this error when building from a clean pi now, didn't before

**Comment by matthew-william-lock** [comment]
Any ideas which ROS2 version is currently working?

**Comment by clalancette** [comment]
So we recently merged support for RTCM messages into the main `ros2` branch.  Unfortunately, `rtcm_msgs` has been having trouble building on the buildfarm, hence the error above.  My [latest fix](https://github.com/tilk/rtcm_msgs/pull/7) should make it build once it is released.

In the meantime, if you checkout both rtcm_msgs and this repository, you should be able to build just fine:

```
mkdir -p ublox_ws/src
cd ublox_ws/src
git clone https://github.com/KumarRobotics/ublox -b ros2
git clone https://github.com/tilk/rtcm_msgs
cd ..
colcon build
```

**Comment by matthew-william-lock** [comment]
@clalancette I will give it a go, thank you!

**Comment by kmhallen** [comment]
It looks like the `humble-devel` branch is mistakenly on the ROS1 branch (`master`)

**Comment by clalancette** [comment]
Yes, good point.  Since we don't use that branch anywhere, I've now removed it.
