### ISSUE TITLE
Example launch command

### ISSUE THREAD

**Issue by matthew-william-lock** [KumarRobotics/ublox#193]
Hey, maybe a silly request but I am looking for an example of how to run the launch file. 

I am currently running 
```
roslaunch ublox_gps ublox_device.launch
```

And getting the following error
```
RLException: arg 'param_file_name' is not defined. 

Arg xml is <arg name="param_file_dir" doc="directory to look for $(arg param_file_name).yaml" default="$(find ublox_gps)/config"/>
The traceback for the exception was written to the log file
```

I understand I need to specify a `node_name` and `param_file_name` but I do not know how to do this.

Thanks!

**Comment by akrv** [comment]
try this command. it might work for you!

`roslaunch ublox_gps ublox_device.launch param_file_name:=zed_f9p node_name:=gps`

zed_f9p is my ublox receiver. check the config folder to use the right param file name.

**Comment by mwlock** [comment]
Thank you! 👼
