### ISSUE TITLE
U-Blox ASIO input buffer read error: End of file, 0

### ISSUE THREAD

**Issue by innavalieva** [KumarRobotics/ublox#20]
Hi!
I am getting the following error all the time:
U-Blox ASIO input buffer read error: End of file, 0
Could you recommend how to resolve this issue?

Best regards,
Inna

**Comment by kartikmohta** [comment]
Try adding the following block on line 118 (i.e. after the serial port is opened) in ublox_gps/src/gps.cpp:
```cpp
{
  // Wait for at least one char on serial port before returning from read.
  // Sadly Boost doesn't provide any way to set this.
  int fd = serial_port->native_handle();
  struct termios tio;
  tcgetattr(fd, &tio);
  tio.c_cc[VTIME] = 0;
  tio.c_cc[VMIN] = 1;
  tcflush(fd, TCIFLUSH);
  tcsetattr(fd, TCSANOW, &tio);
}
```

**Comment by innavalieva** [comment]
Thank you for your suggestion Kartik! 
I have added the block on line 118 in ublox_gps/src/gps.cpp as you suggestaed:


` // open serial port
  try {
    serial->open(port);
  } catch (std::runtime_error& e) {
    throw std::runtime_error("U-Blox: Could not open serial port :" 
                             + port + " " + e.what());
  }

  ROS_INFO("U-Blox: Opened serial port %s", port.c_str());

 //ADDED ON LINE 118 TO FIX ASIO input problem
  {
    // Wait for at least one char on serial port before returning from read.
    // Sadly Boost doesn't provide any way to set this.
    int fd = serial_port->native_handle();
    struct termios tio;
    tcgetattr(fd, &tio);
    tio.c_cc[VTIME] = 0;
    tio.c_cc[VMIN] = 1;
    tcflush(fd, TCIFLUSH);
    tcsetattr(fd, TCSANOW, &tio);
  }
// End of added  ON LINE 118 TO FIX ASIO input problem

  // Set the I/O worker
  if (worker_) return;
  setWorker(boost::shared_ptr<Worker>(
   new AsyncWorker<boost::asio::serial_port>(serial, io_service)));

` // open serial port
  try {
    serial->open(port);
  } catch (std::runtime_error& e) {
    throw std::runtime_error("U-Blox: Could not open serial port :" 
                             + port + " " + e.what());
  }

  ROS_INFO("U-Blox: Opened serial port %s", port.c_str());
 //ADDED ON LINE 118 TO FIX ASIO input problem
  {
    // Wait for at least one char on serial port before returning from read.
    // Sadly Boost doesn't provide any way to set this.
    int fd = serial_port->native_handle();
    struct termios tio;
    tcgetattr(fd, &tio);
    tio.c_cc[VTIME] = 0;
    tio.c_cc[VMIN] = 1;
    tcflush(fd, TCIFLUSH);
    tcsetattr(fd, TCSANOW, &tio);
  }
// End of added  ON LINE 118 TO FIX ASIO input problem

  // Set the I/O worker
  if (worker_) return;
  setWorker(boost::shared_ptr<Worker>(
   new AsyncWorker<boost::asio::serial_port>(serial, io_service)));
`
However the error still exists. 

Best regards,
Inna

**Comment by kartikmohta** [comment]
Did you recompile after adding that code? In its current form, it would give you compile errors. You have to change `serial_port->native_handle();` to `serial->native_handle();` and the recompile.

**Comment by pkess** [comment]
Hi there,
i got the same issue on a raspberry pi with a ros image installed (http://www.german-robot.com/2016/05/26/raspberry-pi-sd-card-image/)

Did anyone solve this?

Additionally i found out that the usb-device disconnects when the code tried to set dtr/rts signals:
dmesg:
`[ 1361.535370] usb 1-1.2: USB disconnect, device number 28
[ 1361.535543] cdc_acm 1-1.2:1.0: failed to set dtr/rts
`

**Comment by weisongwen** [comment]
Hi, @pkess @kartikmohta  
Have you solved this problem, I also get this issue when I use this driver to get data from EVK-M8T. But I can get the data when i use the u-center in windows 10.

Thanks

**Comment by pkess** [comment]
Hi there,
Unfortunately I could not solve this issue, so I decided to start again with a clean raspbian Jessy image and compiled Ros from source. Then tge error was gone.
Took about one day to get all dependencies compiled

**Comment by weisongwen** [comment]
Hi, @pkess ， 
Thanks for your reply. you mean that this is a problem casued by some dependencies needed?

**Comment by weisongwen** [comment]
Hi, @innavalieva  
Have you solved this problem, I also get this issue when I use this driver to get data from EVK-M8T. But I can get the data when i use the u-center in windows 10.

**Comment by billyjov** [comment]
does someone got this driver working on any device?

**Comment by kartikmohta** [comment]
Can you try with the latest commit? That should help with the end of file issue.
There are still some issues with devices with timing features such as the M8T which need to be looked at.

**Comment by billyjov** [comment]
yeah i will try it in a few hours and give a feedback.  

BTW  i use the `GPS U-blox NEO-6M ``.

**Comment by weisongwen** [comment]
Hi @kartikmohta  
I still cannot get data from M8T with driver. just as you said, this driver is not available for M8T by now,

Best 
Welson

**Comment by pec-orange** [comment]
I had this one with NEO-M8P:
U-Blox ASIO input buffer read error: End of file, 0

Solved it by changing lines 419-421 in node.cpp to
if (false) {
       gps.configUsb(usb_tx_, usb_in_, usb_out_);
}

It seems like my node was trying to connect to the device by uart and usb simultaneously. And it was failing since I didn't specify any usb connection parameters in the config file.
Anyway, this is how I fixed it.

P.S.
If it doesn't help - you may also try to remove the corresponding lines in gps.configUsb() function itself. It is located in gps.cpp.

**Comment by siddharthcb** [comment]
> Thank you for your suggestion Kartik!
> I have added the block on line 118 in ublox_gps/src/gps.cpp as you suggestaed:
> 
> ` // open serial port
> try {
> serial->open(port);
> } catch (std::runtime_error& e) {
> throw std::runtime_error("U-Blox: Could not open serial port :"
> + port + " " + e.what());
> }
> 
> ROS_INFO("U-Blox: Opened serial port %s", port.c_str());
> 
> //ADDED ON LINE 118 TO FIX ASIO input problem
> {
> // Wait for at least one char on serial port before returning from read.
> // Sadly Boost doesn't provide any way to set this.
> int fd = serial_port->native_handle();
> struct termios tio;
> tcgetattr(fd, &tio);
> tio.c_cc[VTIME] = 0;
> tio.c_cc[VMIN] = 1;
> tcflush(fd, TCIFLUSH);
> tcsetattr(fd, TCSANOW, &tio);
> }
> // End of added ON LINE 118 TO FIX ASIO input problem
> 
> // Set the I/O worker
> if (worker_) return;
> setWorker(boost::shared_ptr(
> new AsyncWorkerboost::asio::serial_port(serial, io_service)));
> 
> ` // open serial port
> try {
> serial->open(port);
> } catch (std::runtime_error& e) {
> throw std::runtime_error("U-Blox: Could not open serial port :"
> + port + " " + e.what());
> }
> 
> ROS_INFO("U-Blox: Opened serial port %s", port.c_str());
> //ADDED ON LINE 118 TO FIX ASIO input problem
> {
> // Wait for at least one char on serial port before returning from read.
> // Sadly Boost doesn't provide any way to set this.
> int fd = serial_port->native_handle();
> struct termios tio;
> tcgetattr(fd, &tio);
> tio.c_cc[VTIME] = 0;
> tio.c_cc[VMIN] = 1;
> tcflush(fd, TCIFLUSH);
> tcsetattr(fd, TCSANOW, &tio);
> }
> // End of added ON LINE 118 TO FIX ASIO input problem
> 
> // Set the I/O worker
> if (worker_) return;
> setWorker(boost::shared_ptr(
> new AsyncWorkerboost::asio::serial_port(serial, io_service)));
> `
> However the error still exists.
> 
> Best regards,
> ![screenshot from 2017-08-11 10-31-54](https://user-images.githubusercontent.com/27220227/29207230-a410f8a6-7e85-11e7-845d-19ec4f5c6a37.png)
> 
> Inna

had the same error when connected through serial on raspi 4..
