### ISSUE TITLE
Trying to improve GNSS cordinates precision using RTK in ros melodic  

### ISSUE THREAD

**Issue by joseangeldelangel10** [KumarRobotics/ublox#203]
Hi, at @QuantumRoboticsURC we are a team competing in the University Rover Challenge (https://urc.marssociety.org/) and we are trying to improve the accuracy of our GPS module (SparkFun GPS-RTK2 Board - ZED-F9P - https://www.sparkfun.com/products/15136) using RTK, we can't build by ourselves a stationary RTK reciever station, since it would require us to know the accurate GNSS cordinates of it, as far as our understanding goes. Does somebody knows how to get the accurate GNSS cordinates of a point you stand on without internet?

We checked [NTRIP clients](https://blog.emlid.com/what-is-ntrip-and-how-to-use-it-for-rtk-with-reach/) as a possible solution and found some NTRIP clients that interface with ROS ([this one](https://github.com/ros-agriculture/ntrip_ros) for example), but as far as our understanding goes, the robot would need to be conected to internet for NTRIP correction to work.

Is there any possible simple way to make GNSS cordinates have a cm or mm accuracy without internet nor a stationary station developed by our own, also if somebody has a guide or a paper of how RTK works at low level we would really apreciate it <3.   

If its worth something we have 3 of the SparkFun GPS-RTK2 Board - ZED-F9P modules and we are using this GNSS Multi-Band Magnetic Mount Antenna: https://www.sparkfun.com/products/15192 , this Interface Cable SMA to U.FL ( https://www.sparkfun.com/products/9145 ) to connect the antenna and this ROS pkg (ublox)

**Comment by fcladera** [comment]
Hi! There is no free lunch with RTK. It requires to send corrections from a basestation to the rover. For this, you can:
 - Use NTRIP -> requires an internet connection, and you need a local NTRIP caster.
 - Setup your own basestation: you need to configure another gps as basestation, and transmit the corrections to the rover using some kind of communication interface. See the Sparkfun "[How to Build a DIY GNSS Reference Station](https://learn.sparkfun.com/tutorials/how-to-build-a-diy-gnss-reference-station/all)" examples for how to do this.
  - Use a receiver that gets the corrections from the constellation, such as the [PointPerfect](https://www.u-blox.com/en/product/pointperfect) service. There is a product by [SparkFun that does this](https://www.sparkfun.com/products/20000), but you have to pay a subscription for it to work properly.
  
 *If you don't use RTK* there are some more complex solutions that allow you to integrate local odometry sources with GPS. But for this you'll need other sensors, such as LiDAR, or VIO.
