### ISSUE TITLE
Could not open serial port :/dev/ttyUSB0 open: No such file or directory

### ISSUE THREAD

**Issue by rugved-j** [KumarRobotics/ublox#235]
I tried running the ublox_gps_node-launch.py
It gives the following error. 

[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [ublox_gps_node-1]: process started with pid [57937]
[ublox_gps_node-1] terminate called after throwing an instance of 'std::runtime_error'
[ublox_gps_node-1]   what():  U-Blox: Could not open serial port :/dev/ttyUSB0 open: No such file or directory
[ERROR] [ublox_gps_node-1]: process has died [pid 57937, exit code -6, cmd '/home/user/ublox_ws/install/ublox_gps/lib/ublox_gps/ublox_gps_node --ros-args --params-file /home/user/ublox_ws/install/ublox_gps/share/ublox_gps/config/zed_f9p.yaml'].

I expected it to launch successfully. 

I already tried adding my user as member of dialout and giving ownership. 
but still doesn't work.

 - OS: Ubuntu 22.04
 - ROS2 Humble

**Comment by fcladera** [comment]
Did you check what is the default port that the module is using?

List available ports with `ls -al /dev/serial/by-id` and modify the config accordingly.
