### ISSUE TITLE
Bad heading data in ros2 using two zed-f9p receivers

### ISSUE THREAD

**Issue by xaru8145** [KumarRobotics/ublox#236]
Hi,

I have a setup that consists in using 2 **u-blox zed-f9p** receivers from the [simpleRTK2B Heading](https://www.ardusimple.com/product/simplertk2b-heading-basic-starter-kit-ip67/) kit. Both receivers are flashed with **firmware version 1.30**.

One receiver is configured as the moving base and receives ntrip corrections while the other is configured as the rover and receives data from the moving base in order to calculate the heading.

I am seeing an issue where the heading data that comes from the rover is different in I ros1 compared to ros2. I am visualizing the `relPosHeading` field of from the topic `/navrelposned `of msg type `NavRELPOSNED9.msg`.

I have done a static test comparing the heading that comes the rover receiver from 3 different sources: u-center, ros1 and ros2.

1. U-center app from Windows. The heading value is **157.6 deg**
![u_center_rover_relposned](https://github.com/KumarRobotics/ublox/assets/47162887/cc437188-9534-4fbb-b1aa-8b5d1070c5c2)

2.  In ros melodic, using the `master` branch from this repo, the output topic of  /navheading and /navrelposned are the following. The `relPosHeading` field of the `/navrelposned` topic outputs a value of 15674280 1e-5 deg, which is **156.7 deg** and therefore consistent with what we can see in U-center.
![ros1_melodic_navposrelned](https://github.com/KumarRobotics/ublox/assets/47162887/24c9e3c6-77cf-4a7f-ae64-e0f5217f88a4)

3. In ros2 foxy  I tried to use the branch `foxy-devel` from this repo but it did not provide support for forwarding rtcm corrections from ntrip and also the /`navrelposned` message was all 0's. I created a fork in my personal repo (branch: [ros2-foxy](https://github.com/xaru8145/ublox/tree/ros2-foxy)) from your most recent commit in the `ros2` branch and made some slight modifications so it compiles in foxy. However, as it can be seen in the image below, the value `rel_pos_heading` in `/navrelposned` topic is 22740368 1e-5 deg (227.4 deg) and the rel_pos_length field is 10969555cm and the baseline is 50cm (as it can be seen in the image above in ros1). 
![ros2_foxy_navposrelned](https://github.com/KumarRobotics/ublox/assets/47162887/1c1e9e96-1880-47cd-b25f-c5afc9b1e505)

Also, when I rotate the robot in yaw, both the u-center viewer and the topic in ros1 melodic show a consistent and coherent change in the heading. However, in ros2 it seems like this value does not change and always remains 227.4 deg. Some decimals in the last positions change but less than 1 degree.

Has someone experienced a similar issue? I am happy to provide rosbags or more documentation.

Thanks in advance!

**Comment by bnbhat** [comment]
Hey!

I am also trying to do the same with a pair of **u-blox zed-f9p** and **u-blox zed-f9h** modules.
I set them up in u-center and it is working. But, I'm having difficulties configuring them with this driver as a moving base and a rover. 

Would you mind sharing your configuration files? It would be a great help to me!

Thanks in advance!

**Comment by xaru8145** [comment]
Hi  @bnbhat !

If you see your data correctly in the u-center, it means that the receiver is well configured. 

If they are not when you launch the driver, I am guessing that you are trying to override the configuration through setting ros parameters through the driver. In order to avoid this, try setting the `config_on_startup` parameter to `false`. 

You just then need to specify the right port, the baudrate and which topics you want to publish, like on the example [config file](https://github.com/KumarRobotics/ublox/blob/master/ublox_gps/config/zed_f9p.yaml) provided in this package.

Are you using ros2? Let me know if you experience the same issues with the heading output data from the driver if you use ros2. Thanks!

**Comment by bnbhat** [comment]
Thank you so much! @xaru8145 

As you suggested, I changed `config_on_startup` to `false` and it is working now!

Yes, I am using ROS 2 Humble. For now, it seems the heading is the same as what I can see in the u-center.



<div style="display: flex; justify-content: space-between;">
  <img src="https://github.com/KumarRobotics/ublox/assets/66437415/1a96665a-f02b-42c4-8d6c-36739d712e5f" alt="Image 1" width="45%">
  <img src="https://github.com/KumarRobotics/ublox/assets/66437415/160cc5d2-7e4a-42c9-97ba-6b8c742360e9" alt="Image 2" width="41.1%">
</div>
  
   
Here you can find my configurations [https://github.com/Lemvos/ublox_ros2_driver.git](url)
u-center config for f9p as a moving base [https://gist.github.com/bnbhat/c27f6d7f87c88cf15f6a0633b90dcc80](url)

Let me know if you need any information about my setup.

**Comment by xaru8145** [comment]
Thanks @bnbhat ! I tried using 2.3.0 release in humble and it works just fine. It seems that porting the 2.3.0 release from humble to foxy and making it compile is not enough. There must be something related to differences in how these 2 ROS distros serialize messages. Best thing is to forget about foxy and move to humble

**Comment by ciniminis1** [comment]
Hi @xaru8145 , I plan to use the same setup to get a heading information. Please, is the heading north/east referenced or strictly relative? Thank you.
