### ISSUE TITLE
Running the driver on Raspberry PI

### ISSUE THREAD

**Issue by Hasan-ta** [KumarRobotics/ublox#26]
I have a raspberry PI loaded with Ubuntu and ROS Kinetic. The driver compiles and runs on the raspberry PI but doesn't publish the requested topics, although the same driver runs fine on x86 based system also with ROS Kinetic. Anyone had a similar issue?

**Comment by billyjov** [comment]
@Hasan-ta Yeah I ran into the same issue. But dont know why i got the `status = -1` and i'm be able to read data.

**Comment by billyjov** [comment]
![bildschirmfoto vom 2018-03-29 15-53-59](https://user-images.githubusercontent.com/18737653/38092904-c9f5fc26-3369-11e8-94d4-ae22ca39e49b.png)
![bildschirmfoto vom 2018-03-29 15-54-23](https://user-images.githubusercontent.com/18737653/38092905-ca0fd1dc-3369-11e8-96ef-37b8c0acb477.png)

**Comment by sidtanwar** [comment]
I have the same issue as @Hasan-ta . I am using a Ublox LEA-6T receiver with Raspberry Pi and ROS Indigo.  Has someone come up with a solution yet?

**Comment by mistoll** [comment]
Should be fixed by e255881

**Comment by fcladera** [comment]
Closed as it is a stale issue. Feel free to reopen it if you still are facing this problem.
