### ISSUE TITLE
Setting node_name arg

### ISSUE THREAD

**Issue by MarcoMers** [KumarRobotics/ublox#49]
When i try to run the launch file inside: ublox_gps --> launch --> ublox_device.launch  it doesn't work and output this message:

![problemino](https://user-images.githubusercontent.com/45452478/54369619-88fedc80-4676-11e9-8876-4ef4006cf6f6.PNG)

My question is: where and how configure "node_name" ???
Here there are the "ublox_device.launc" launcher:
![problemino2](https://user-images.githubusercontent.com/45452478/54370082-50abce00-4677-11e9-999d-2e044fe6c5b5.PNG)

**Comment by versatran01** [comment]
roslaunch ublox_device.launch node_name:=<name>

**Comment by MarcoMers** [comment]
It doesn't work....

**Comment by versatran01** [comment]
How does it not work? Do you have any error messages?

**Comment by BartVanderHaagen** [comment]
<arg name="node_name"           doc="name of this node"
