### ISSUE TITLE
missing install commands for launch and config files

### ISSUE THREAD

**Issue by amc-nu** [KumarRobotics/ublox#52]
The `ublox_gps` package CMakefile is missing install commands for the `launch` and `config` directories.
https://github.com/KumarRobotics/ublox/blob/master/ublox_gps/CMakeLists.txt#L57

```
install(DIRECTORY config/
  DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}/config
  PATTERN ".svn" EXCLUDE
)

install(DIRECTORY launch/
  DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}/launch
  PATTERN ".svn" EXCLUDE
)
```

**Comment by versatran01** [comment]
Thanks, I updated the CMakeLists accordingly.
