### ISSUE TITLE
NavSat message flags means? Help!

### ISSUE THREAD

**Issue by MarcoMers** [KumarRobotics/ublox#63]
Hello everyone, recently i have logged a bag file which contain navsat topic, the topic have this structure: http://docs.ros.org/kinetic/api/ublox_msgs/html/msg/NavSAT_SV.html

**My question is: How to read and what does it mean the flags message???**

Here i attach a pic :
![IMG_20190906_101021](https://user-images.githubusercontent.com/45452478/64412101-f07a6f80-d08e-11e9-96c0-980be2a48381.jpg)

Thank you for the help!

**Comment by versatran01** [comment]
flags is a bitmask as shown in the link you attached, you can decode it by some bitwise operations.

**Comment by MarcoMers** [comment]
Thank you, could you send me the link of  the file where is explained how to decode the bitmask or explain how to do it?
Thank you for the  help.

**Comment by versatran01** [comment]
You already have it, which is the link you attached. 
You can google bitmask for more info.
