### ISSUE TITLE
multiple gps devices

### ISSUE THREAD

**Issue by ymkim92** [KumarRobotics/ublox#7]
Hello,

I have one more question.
I have multiple ublox devices and I can run following commands.

```
$ roslaunch ublox_gps ublox_gps.launch

$ roslaunch ublox_gps ublox_gps.launch device:=/dev/ttyACM1
```

But, how can I access to the msgs from differrent ublox devices?
`$ rostopic list` returns only one msgs.

Regards,
Kim

**Comment by ArjunBalakrishnan** [comment]
Hello,
I followed this suggestion and created a launch file as given below. It creates two different nodes _gps1_ and _gps2_. But topics are only published in one of them. What could be the error? I highly appreciate any suggestions.  

`<launch>
  <arg name="output" default="screen" />
  <arg name="respawn" default="true" />
  <arg name="respawn_delay" default="30" />
  <arg name="clear_params" default="true" />

  <node pkg="ublox_gps" type="ublox_gps" name="gps1"
        output="$(arg output)" 
        clear_params="$(arg clear_params)"
        respawn="$(arg respawn)" 
        respawn_delay="$(arg respawn_delay)">
    <rosparam command="load" 
              file="$(find ublox_gps)/config/gps1.yaml" />
  </node>

  <node pkg="ublox_gps" type="ublox_gps" name="gps2"
        output="$(arg output)" 
        clear_params="$(arg clear_params)"
        respawn="$(arg respawn)" 
        respawn_delay="$(arg respawn_delay)">
    <rosparam command="load" 
              file="$(find ublox_gps)/config/gps2.yaml" />
  </node>
</launch>`

Thank you
