### ISSUE TITLE
Metapackage dependencies

### ISSUE THREAD

**Issue by msadowski** [KumarRobotics/ublox#74]
Hi!

I'm just starting to use your package. I think the package.xml in ublox directory should specify ublox_gps, ublox_msgs and ublox_serialization as dependencies. Then, when you install the package via `apt-get install ros-melodic-ublox` then all dependencies should be installed correctly.

I'm happy to make a PR for this if it's helpful.

**Comment by versatran01** [comment]
Please do. Thanks!
