### ISSUE TITLE
Error : U-blox: received NACK

### ISSUE THREAD

**Issue by WbHappy** [KumarRobotics/ublox#79]
Hello,

Thanks for the package I have been using it for quite some time with an EVK-7P.

I recently bought a EVK-M8U and I have been struggling with errors that makes this development kit unusable... Here is the print of the error when debug parameter is set at 1 :

```bash
process[ublox_m8u-2]: started with pid [6872]
[ INFO] [1582558977.916018067]: U-Blox: Opened serial port /dev/ttyACM0
[DEBUG] [1582558977.916223076]: Configuring UART1 baud rate: 115200, In/Out Protocol: 1 / 2
[DEBUG] [1582558977.920783874]: EXT CORE 3.01 (1ec93f), HW VER: 00080000
[DEBUG] [1582558977.920811168]: ROM BASE 2.01 (75331)
[DEBUG] [1582558977.920817646]: FWVER=UDR 1.21
[DEBUG] [1582558977.920822781]: PROTVER=19.20
[DEBUG] [1582558977.920831824]: MOD=NEO-M8U-0
[DEBUG] [1582558977.920840261]: FIS=0xEF4015 (84524)
[DEBUG] [1582558977.920849343]: GPS;GLO;GAL;BDS
[DEBUG] [1582558977.920858546]: SBAS;IMES;QZSS
[ INFO] [1582558977.920880726]: U-Blox Firmware Version: 8
[ WARN] [1582558977.942375333]: ROS Diagnostics specific to u-blox ADR/UDR devices is unimplemented. See AdrUdrProduct class in node.h & node.cpp.
[DEBUG] [1582558977.942403975]: Configuring measurement rate to 250 ms and nav rate to 4 cycles
[DEBUG] [1582558977.943039965]: Configuring SBAS: usage 1, max_sbas 0
[DEBUG] [1582558977.943742464]: Disabling PPP
[ERROR] [1582558977.944578522]: U-blox: received NACK: 0x06 / 0x23
[FATAL] [1582558977.944667048]: Error configuring u-blox: Failed to disable PPP.
[ERROR] [1582558977.945527244]: U-Blox ASIO input buffer read error: Operation canceled, 0
[ INFO] [1582558977.945586391]: Closed connection to /dev/ttyACM0.
[ublox_m8u-2] process has finished cleanly
```

I precise that this EVK M8U works fine on Windows's U-Center.

Before posting this issue I looked a bit at how to fix and here is also my dirty workaround.
Error displayed previously is triggered because of disabling PPP functionality. Disabling PPP is done by the method `setPpp` line 455 of src/node.cpp, I commented the full block (liens 455 to 458).. 

Next error is : 
``` bash
process[ublox_m8u-2]: started with pid [12835]
[ INFO] [1582559130.450352861]: U-Blox: Opened serial port /dev/ttyACM0
[DEBUG] [1582559130.450729744]: Configuring UART1 baud rate: 115200, In/Out Protocol: 1 / 2
[DEBUG] [1582559130.454792017]: EXT CORE 3.01 (1ec93f), HW VER: 00080000
[DEBUG] [1582559130.454896389]: ROM BASE 2.01 (75331)
[DEBUG] [1582559130.455063274]: FWVER=UDR 1.21
[DEBUG] [1582559130.455147505]: PROTVER=19.20
[DEBUG] [1582559130.455202968]: MOD=NEO-M8U-0
[DEBUG] [1582559130.455287552]: FIS=0xEF4015 (84524)
[DEBUG] [1582559130.455352122]: GPS;GLO;GAL;BDS
[DEBUG] [1582559130.455407759]: SBAS;IMES;QZSS
[ INFO] [1582559130.455499582]: U-Blox Firmware Version: 8
[ WARN] [1582559130.561418116]: ROS Diagnostics specific to u-blox ADR/UDR devices is unimplemented. See AdrUdrProduct class in node.h & node.cpp.
[DEBUG] [1582559130.561513553]: Configuring measurement rate to 250 ms and nav rate to 4 cycles
[DEBUG] [1582559130.562403695]: Configuring SBAS: usage 1, max_sbas 0
[DEBUG] [1582559130.563217725]: Setting dynamic model to 0
[DEBUG] [1582559130.563945310]: Setting fix mode to 3
[DEBUG] [1582559130.564995635]: Setting DR Limit to 0
[DEBUG] [1582559130.567321972]: Read GNSS config.
[DEBUG] [1582559130.567396911]: Num. tracking channels in hardware: 28
[DEBUG] [1582559130.567439278]: Num. tracking channels to use: 28
[DEBUG] [1582559130.567596408]: Galileo GNSS Configuration is different
[DEBUG] [1582559130.567669093]: Re-configuring GNSS.
[ WARN] [1582559130.569029918]: GNSS re-configured, cold resetting device.
[ WARN] [1582559130.569126551]: Resetting u-blox. If device address changes, node must be relaunched.
[ERROR] [1582559131.570413209]: U-Blox ASIO input buffer read error: Operation canceled, 0
[ INFO] [1582559146.571430061]: U-Blox: Reset serial port /dev/ttyACM0
[DEBUG] [1582559146.573829678]: Enabling ADR/UDR
[ERROR] [1582559146.574597604]: U-blox: received NACK: 0x06 / 0x23
[FATAL] [1582559146.574938008]: Error configuring u-blox: Failed to enableuse_adr
[ERROR] [1582559146.576165756]: U-Blox ASIO input buffer read error: Operation canceled, 0
[ INFO] [1582559146.576379704]: Closed connection to /dev/ttyACM0.
[ublox_m8u-2] process has finished cleanly
```

This time the error is regarding some enable_use_adr. I commented the block, line 1290 to 1292 in src/node.cpp that contains the `setUseAdr` method responsable for my error.

And finally I managed to use the EVK M8U...

I obviously agree that this is totally a dirty fix but only a temporary workaround. 
I would appreciate a cleaner fix in the future but at least this post might help a bit ;).
Or... an explanation if other people also have the EVK M8U that works without the need of all those fixes..

**Comment by riebl** [comment]
We have observed the same issue in the past. The actual reason for this behaviour is the changed protocol by recent firmware versions of M8U. This has been fixed by #89.

**Comment by WbHappy** [comment]
Thanks for the answer, I will check this.

I close the issue for now then.

**Comment by Muhammad540** [comment]
> We have observed the same issue in the past. The actual reason for this behaviour is the changed protocol by recent firmware versions of M8U. This has been fixed by #89.

Hey @riebl , i was working with the ros2 branch for the ublox-m8u module and experienced this issue of firmware version. Following the merge commit history #89, i have fixed the issue ros2 branch. If you would like to see the changes in this branch, i can open a PR for this fix.

**Comment by riebl** [comment]
Hi @Muhammad540, I think you should discuss with the project maintainers if your changes should get merged.
I am no longer using this ROS ublox node for various reasons.

**Comment by Muhammad540** [comment]
> Hi @Muhammad540, I think you should discuss with the project maintainers if your changes should get merged. I am no longer using this ROS ublox node for various reasons.

got it, thanks for letting me know.
