### ISSUE TITLE
Is it possible to get IMU message from ublox EVK_M8L?

### ISSUE THREAD

**Issue by qazmichaelgw** [KumarRobotics/ublox#9]
I am going to use ublox for GPS navigation. However, in order to integrate to ROS, we need IMU data. 
Is there any way to transfrom the /gps/navvelned to /Imu/data.
http://docs.ros.org/api/sensor_msgs/html/msg/Imu.html
Thanks a lot!

**Comment by vmlane** [comment]
You'd have to create your own node to do this, but I'm not sure why you would want to, since GPS data isn't IMU data. It would make more sense to use a NavSatFix message for GPS data. If you're talking about sensor fusion that's another matter, and isn't handled by this repo.
